// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    coindrip
    (
        init => init
        createStream => create_stream
        recipientBalance => recipient_balance
        senderBalance => sender_balance
        claimFromStream => claim_from_stream
        cancelStream => cancel_stream
        claimFromStreamAfterCancel => claim_from_stream_after_cancel
        getStreamData => get_stream
        getStreamListByAddress => streams_list
        getLastStreamId => last_stream_id
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
